---

- block:

    - block:
        - name: install broadcom bcm43 drivers
          package:
            name: "{{ hardware_broadcom_bcm43 }}"
            state: present

      when:
        - '"Network controller: Broadcom Inc. and subsidiaries BCM43" in t_hardware_lscpi.stdout'

  when: ansible_system == "Linux"
